# A generic, single database configuration.

[alembic]
# path to migration script directory
script_location = alembic

# template used to generate migration file names
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file as
# well as the filename.
# timezone =

# max length of characters in --autogenerate generated filenames
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# version location specification; this defaults
# to alembic/versions. When using multiple version
# directories, initial revisions must be created with --version-path
# version_locations = %(here)s/bar:%(here)s/bat:alembic/versions

# set to 'true' to search source files recursively
# in each "version_locations" directory
# recursive_version_locations = false

# set to 'true' to allow Alembic to run if the database
# offline engine fails to connect
# allow_offline = false

sqlalchemy.url = postgresql://architect_user:architect_secure_password@localhost:5432/architectiq_db

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
