"""add_project_questionnaires_table

Revision ID: 239b1797ee29
Revises: '001_create_phase2_tables'
Create Date: 2026-08-02 17:45:56.396965

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '239b1797ee29'
down_revision: Union[str, None] = '001_create_phase2_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_questionnaires',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_questionnaires_id'), 'project_questionnaires', ['id'], unique=False)
    op.create_index(op.f('ix_project_questionnaires_project_id'), 'project_questionnaires', ['project_id'], unique=True)
    op.drop_constraint('project_workspaces_project_id_key', 'project_workspaces', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('project_workspaces_project_id_key', 'project_workspaces', ['project_id'])
    op.drop_index(op.f('ix_project_questionnaires_project_id'), table_name='project_questionnaires')
    op.drop_index(op.f('ix_project_questionnaires_id'), table_name='project_questionnaires')
    op.drop_table('project_questionnaires')
    # ### end Alembic commands ###
